name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests
      run: |
        pnpm run lint
        pnpm run type-check
        pnpm test
        pnpm run build
        
    - name: Check if version exists on npm
      id: check-version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "current_version=$VERSION" >> $GITHUB_OUTPUT
        
        if npm view pathao-merchant-sdk@$VERSION version > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Version $VERSION already exists on npm"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Version $VERSION is new and can be published"
        fi
        
    - name: Publish to npm
      if: steps.check-version.outputs.exists == 'false'
      run: pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      if: steps.check-version.outputs.exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.check-version.outputs.current_version }}
        release_name: Release v${{ steps.check-version.outputs.current_version }}
        body: |
          ## Release v${{ steps.check-version.outputs.current_version }}
          
          This release was automatically published to npm.
          
          ### Installation
          ```bash
          npm install pathao-merchant-sdk@${{ steps.check-version.outputs.current_version }}
          ```
          
          ### Changes
          See [CHANGELOG.md](./CHANGELOG.md) for detailed changes.
        draft: false
        prerelease: false
